# Generated by Django 4.2.11 on 2024-07-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_filmwork_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="file_path",
            field=models.FileField(
                blank=True, null=True, upload_to="movies/", verbose_name="file"
            ),
        ),
        migrations.AddField(
            model_name="filmwork",
            name="persons",
            field=models.ManyToManyField(
                through="movies.PersonFilmwork", to="movies.person"
            ),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="type",
            field=models.CharField(
                choices=[("movie", "movie"), ("tv_show", "tv_show")],
                default="movie",
                verbose_name="type",
            ),
        ),
        migrations.AddConstraint(
            model_name="genrefilmwork",
            constraint=models.UniqueConstraint(
                fields=("genre_id", "film_work_id"),
                name="genre_film_work_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="personfilmwork",
            constraint=models.UniqueConstraint(
                fields=("filmwork_id", "person_id", "role"),
                name="person_film_work_unique",
            ),
        ),
    ]
